{{- if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "opendistro-es.fullname" . }}-ca
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
spec:
  secretName: {{ template "opendistro-es.fullname" . }}-ca-cert
  duration: {{ .Values.certmanager.ca.duration }}
  keySize: {{ .Values.certmanager.ca.keySize }}
  renewBefore: {{ .Values.certmanager.ca.renewBefore }}
  keyAlgorithm: rsa
  keyEncoding: pkcs8
  isCA: true
  commonName: {{ .Values.certmanager.ca.commonName }}
  usages:
{{- if .Values.certmanager.ca.usages }}
{{ toYaml .Values.certmanager.ca.usages| indent 2 }}
{{- end }}
  organization:
{{- if .Values.certmanager.ca.organization }}
{{ toYaml .Values.certmanager.ca.organization| indent 2 }}
{{- end }}
  issuerRef:
    name: {{ template "opendistro-es.fullname" . }}-selfsigned
    kind: Issuer
{{- end }}