name: WhiteSource Vulnerability Scan

on:
  schedule:
    - cron: '30 10 * * *'
  repository_dispatch:
    types: [check-vulnerability-whitesource]

jobs:
  whitesource-vulnerability-scan:
    name: WhiteSource Vulnerability Scan
    runs-on: ubuntu-18.04
    timeout-minutes: 80
    strategy:
      fail-fast: false
      matrix:
        java: [11]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Vulnerability Scan
        env:
          wss_apikey: ${{ secrets.WSS_API_KEY }}
        run: |
          cd standalone-tools
          ./wss-scan.sh
          cat whitesource/*/*

      - name: Send mail
        if: ${{ always() }}
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ODFE Vulnerability and License Scan - Daily Run 
          body: file://standalone-tools/output.md
          to: odfe-infra-team@amazon.com
          from: Opendistro Elasticsearch
          content_type: text/html
