name: Sync ami artifacts to Prod

on: 
  repository_dispatch:
    types: [prod-sync-ami]

jobs:
  Sync-AMI-Prod:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1

      - name: Getting OD version
        run: |
          OD_VERSION=`./bin/version-info --od`
          echo "::set-env name=od_version::$OD_VERSION"
    
      - name: Set AMI from private to public in all regions
        run: |
          #!/bin/bash
 
          # The actions aws credential above would lock region
          # This is to allow aws to switch region in order to 
          # make AMI public on all available regions
          aws configure set aws_access_key_id ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
         
          REGIONS_LIST=`aws ec2 describe-regions --query 'Regions[].RegionName[]' --output text`
          for region_name in $REGIONS_LIST
          do
            echo "Set region: ${region_name}"
            aws configure set region $region_name
            aws configure list | grep region | awk '{print $2}'
            
            echo "Making AMI Public in region (${region_name}): Open Distro for Elasticsearch-${{ env.od_version }}"
            AMI_IMAGE_ID=`aws ec2 describe-images --filters "Name=name,Values=Open Distro for Elasticsearch-${{ env.od_version }}*" --query 'Images[*].{ID:ImageId}' --output text`
            #AMI_IMAGE_ID=`aws ec2 describe-images --filters "Name=name,Values=Open Distro for Elasticsearch-1.6.0*" --query 'Images[*].{ID:ImageId}' --output text`
            aws ec2 modify-image-attribute --image-id "${AMI_IMAGE_ID}" --launch-permission "Add=[{Group=all}]"
          done

          echo "AMI has been published / set to public on all regions"

