name: Staging Build Release Candidate

on:
#  schedule:
#    - cron: '30 10 * * *' 

#  repository_dispatch:
#    types: [staging-build-release-candidate]
  push:
    branches: [sreekarj_V300226520]

jobs:
  Staging-Build-Release-Candidate:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install python packages
        run: |
          sudo pip install boto3
          sudo pip install pyyaml
          sudo pip install requests
    
      - name: Moving artifacts from snapshots to release folder
        run: |
          cd release-tools/scripts
          ./staging-build-release-candidate.py ${GITHUB_RUN_ID}
