name: Build macOS using tar artifacts

on:
#  schedule:
#    - cron: '0 12 * * *'
#  repository_dispatch:
#    types: [staging-build-macos]
  push:
    branches: [sreekarj_macos]

jobs:
  build-es-artifacts-x64:
    name: Build macOS ES Artifacts X64
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set Up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Required Packages
      run: ./release-tools/scripts/required_packages.sh

    - name: Build macOS
      env:
        install4j_license: ${{ secrets.INSTALL4J_LICENSE }}
      run: ./elasticsearch/windows/opendistro-macos-build.sh macos x64
       


  build-kibana-artifacts-arm64:
    needs: [plugin-availability, Provision-Runners]
    name: Build KIBANA Artifacts ARM64
    runs-on: [self-hosted, Linux, ARM64, odfe-tar-build-kibana-arm64]
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Required Packages
        run: ./release-tools/scripts/required_packages.sh
      - name: Build Kibana
        run: ./kibana/linux_distributions/opendistro-kibana-build.sh tar macos x64
